### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dtch1997** [dtch1997/gpt-text-gym#1]
- [ ] Implement GPT-4 request interface
- [ ] Add environments 
- [ ] Implement evaluation loop on text-wrapped Gym environments
- [ ] Evaluate baseline GPT on environments
